/*
 * TaggerDemo2.java
 *
 */

package de.marbach.bachelor.analysis;


import de.marbach.bachelor.model.NodeElement;
import edu.stanford.nlp.dcoref.CorefChain;
import edu.stanford.nlp.dcoref.CorefCoreAnnotations;
import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.pipeline.Annotation;
import edu.stanford.nlp.pipeline.StanfordCoreNLP;
import edu.stanford.nlp.semgraph.SemanticGraph;
import edu.stanford.nlp.semgraph.SemanticGraphCoreAnnotations;
import edu.stanford.nlp.trees.Tree;
import edu.stanford.nlp.trees.TreeCoreAnnotations;
import edu.stanford.nlp.util.CoreMap;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Scanner;


/**
 * This demo shows user-provided sentences (i.e., {@code List<HasWord>})
 * being tagged by the tagger. The sentences are generated by direct use
 * of the DocumentPreprocessor class.
 *
 * @author Christopher Manning
 */
public class StanfordTagger {
	protected StanfordCoreNLP pipeline;

	public StanfordTagger() {
		Properties props = new Properties();
		props.setProperty("annotators", "tokenize, ssplit, pos, lemma");
		pipeline = new StanfordCoreNLP(props);
	}

	public void annotate(File file, Map<String, NodeElement> allNodes) throws IOException {
		String content = new String(Files.readAllBytes(file.toPath()));

		// create an empty Annotation just with the given text
		Annotation document = new Annotation(content);

		// run all Annotators on this text
		pipeline.annotate(document);

		// these are all the sentences in this document
		// a CoreMap is essentially a Map that uses class objects as keys and has values with custom types
		List<CoreMap> sentences = document.get(CoreAnnotations.SentencesAnnotation.class);

		for (CoreMap sentence : sentences) {
			// traversing the words in the current sentence
			// a CoreLabel is a CoreMap with additional token-specific methods
			for (CoreLabel token : sentence.get(CoreAnnotations.TokensAnnotation.class)) {
				// this is the text of the token
				String word = token.get(CoreAnnotations.TextAnnotation.class).toLowerCase();
				// this is the POS tag of the token
				String pos = token.get(CoreAnnotations.PartOfSpeechAnnotation.class);
				//String lemma = token.get(CoreAnnotations.LemmaAnnotation.class);

				if (allNodes.containsKey(word)) {
					NodeElement nodeElement = allNodes.get(word);
					nodeElement.addTag(pos);
				}
			}
		}
	}

}
